# Generated by Django 3.0.5 on 2020-06-13 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
                ('gender', models.CharField(max_length=10)),
                ('coun', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=13)),
                ('img', models.ImageField(upload_to='media')),
                ('Address', models.CharField(max_length=200)),
            ],
        ),
    ]
