# Generated by Django 3.0.5 on 2020-06-13 11:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0002_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='active',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
