# Generated by Django 3.0.5 on 2020-06-13 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0003_active_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='active',
            name='date',
            field=models.TimeField(),
        ),
    ]
