# Generated by Django 3.0.5 on 2020-06-13 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0004_auto_20200613_2245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='active',
            name='date',
            field=models.CharField(max_length=200),
        ),
    ]
