# Generated by Django 2.2.2 on 2020-06-20 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0008_auto_20200620_1318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='active',
            name='online',
            field=models.BooleanField(default=False),
        ),
    ]
