# Generated by Django 2.2.2 on 2020-06-20 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0009_auto_20200620_1325'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='active',
            name='online',
        ),
        migrations.AddField(
            model_name='active',
            name='status',
            field=models.CharField(default='Offline', max_length=10),
        ),
    ]
