# Generated by Django 2.2.2 on 2020-06-20 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0010_auto_20200620_1409'),
    ]

    operations = [
        migrations.AddField(
            model_name='active',
            name='name',
            field=models.CharField(default='', max_length=200),
        ),
    ]
